<a href="https://colab.research.google.com/github/barath-kumar-S-A/Deep-Learning/blob/main/Tensorflow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## create a scalar tensor

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tf.constant(4,shape=(1,1),dtype=tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [ ]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
tf.random.normal((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.014538  ,  0.4720134 , -1.6008679 ],
       [-1.400796  , -1.2564914 ,  1.1029102 ],
       [ 0.6487013 , -0.44481984,  0.4773028 ]], dtype=float32)>

In [ ]:
tf.random.uniform((3,3),minval=0,maxval=4)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.7829847, 3.675272 , 1.0843549],
       [2.5792422, 2.0107207, 2.0815144],
       [2.422185 , 3.9910278, 3.7265139]], dtype=float32)>

In [ ]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

##mathematical operation

In [ ]:
x =[[1,2,3],[2,3,3],[3,2,3],[4,3,4]]
y = [[1,2,3],[2,3,3],[3,2,3],[4,3,4]]

In [ ]:
z = tf.add(x,y)
print(z)

tf.Tensor(
[[-0.07959859  2.1450074  -0.18934302]
 [-0.6380804   2.1167853   1.0696832 ]
 [-0.07845116 -0.18902045  1.3920321 ]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.constant(4,shape=(1,1))
y = tf.constant(4,shape=(1,1))

In [ ]:
print(x @ y)

tf.Tensor([[16]], shape=(1, 1), dtype=int32)


In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[16]], dtype=int32)>